<?php
//	Load functions for the module.
module_load_include('inc', 'feeds_node_autosync', 'feeds_node_autosync.data');
module_load_include('inc', 'feeds_node_autosync', 'feeds_node_autosync.feeds_hooks');
module_load_include('inc', 'feeds_node_autosync', 'feeds_node_autosync.forms_hooks');
module_load_include('inc', 'feeds_node_autosync', 'feeds_node_autosync.node_hooks');

/**
 * Implements hook_help()
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
*/
function feeds_node_autosync_help($path, $arg) {
	switch ($path) {
		case "admin/help#feeds_node_autosync":
			return '<p>' . t("Connect nodes to their defined feed URL for automatic updates!") . '</p>';
			break;
	}
}

/**
 * Implements hook_enable()
 *
 * !remove Mostly for development purposes... remove for release
 * Ensures that installation script is re-run with disable, re-enable 
 *
 */
function feeds_node_autosync_enable() {
	feeds_node_autosync_install();
}

/**
 * Implements hook_permission()
 * 
 * defined the permissions levels which control pieces of the module's functionality.
 */
function feeds_node_autosync_permission() {
	return array(
			'fna bundle configuration form' => array(
					'title' => t('Configure bundles with Feeds Node Auto-sync'),
					'description' => t('Access the auto-sync configuration on bundles (E.g. Articles)'),
			),
			'fna bundle protect fields form' => array(
					'title' => t('Configure Feeds Node Auto-sync fields to be protected'),
					'description' => t('Modify the on/off of protected fields in Feeds Node Auto-sync.'),
			),
			'fna edit protected fields' => array(
					'title' => t('Bypass uneditable field setting'),
					'description' => t('Configuration allows bundled fields to be uneditable with the form. This permission bypasses that.'),
			),
				
	);
}

